# Generated by Django 5.0.2 on 2024-03-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'client'), ('MARCHAND', 'marchand'), ('ADMIN', 'admin')], max_length=32),
        ),
    ]
