# Generated by Django 5.0.3 on 2024-03-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'client'), ('MARCHAND', 'marchand'), ('ADMIN', 'admin')], default='', max_length=32),
        ),
    ]
