# Generated by Django 5.0.3 on 2024-05-02 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cathegorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('thumbs', models.ImageField(blank=True, upload_to='Cathegorie/images/')),
                ('id_modele', models.ManyToManyField(related_name='cathegories', to='app.modele')),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(blank=True)),
                ('qt_stock', models.IntegerField(blank=True)),
                ('thumbs', models.ImageField(blank=True, upload_to='Pieces/images/')),
                ('city', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('id_cathegorie', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='store.cathegorie')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(blank=True, default=0)),
                ('commande_date', models.DateField(auto_now_add=True)),
                ('Statut', models.BooleanField(default=False)),
                ('piece', models.ManyToManyField(default=0, related_name='commandes', to='store.piece')),
            ],
        ),
    ]
