# Generated by Django 5.0.2 on 2024-02-23 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cathegorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Cathegorie', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='Cathegorie/images/')),
                ('id_voiture', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.voiture')),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('qt_stock', models.IntegerField()),
                ('image', models.ImageField(upload_to='Pieces/images/')),
                ('city', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('id_cathegorie', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.cathegorie')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('commande_date', models.DateField(auto_now_add=True, null=True)),
                ('Statut', models.BooleanField(default=False)),
                ('piece', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='store.piece')),
            ],
        ),
    ]
