# Generated by Django 5.0.2 on 2024-03-11 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cathegorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='Cathegorie/images/')),
                ('id_modele', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.modele')),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(null=True)),
                ('qt_stock', models.IntegerField(null=True)),
                ('image', models.ImageField(null=True, upload_to='Pieces/images/')),
                ('city', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('id_cathegorie', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.cathegorie')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(default=0, null=True)),
                ('commande_date', models.DateField(auto_now_add=True)),
                ('Statut', models.BooleanField(default=False)),
                ('piece', models.ManyToManyField(default=0, related_name='product_commande', to='store.piece')),
            ],
        ),
    ]
