# Generated by Django 5.0.2 on 2024-02-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_piece_id_cathegorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='piece',
        ),
        migrations.AddField(
            model_name='commande',
            name='piece',
            field=models.ManyToManyField(default=0, related_name='product_commande', to='store.piece'),
        ),
    ]
