# Generated by Django 5.0.3 on 2024-05-07 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_piece_thumbs_pieceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieceimage',
            name='thumbs',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbs', to='store.piece'),
        ),
    ]
