# Generated by Django 5.0.4 on 2024-05-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_pieceimage_thumbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieceimage',
            name='public_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
