# Generated by Django 5.0.3 on 2024-05-23 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('store', '0005_piece_modele'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='id_marque',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='marqe', to='app.marque'),
            preserve_default=False,
        ),
    ]
