# Generated by Django 5.0.4 on 2024-05-17 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('store', '0007_rename_statut_commande_status_commande_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='client_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_id', to='account.client'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='city',
            field=models.CharField(default='yaounde', max_length=255),
        ),
    ]
