# Generated by Django 5.0.3 on 2024-06-07 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_piece_id_marque'),
        ('store', '0008_alter_commande_client_id_alter_piece_city'),
    ]

    operations = [
    ]
