# Generated by Django 5.0.3 on 2024-06-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_commande_operator_commande_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='piece_qte',
            field=models.CharField(default=(1, 2), max_length=256),
            preserve_default=False,
        ),
    ]
