# Generated by Django 5.0.3 on 2024-06-20 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_otherclient_email'),
        ('store', '0011_commande_piece_qte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='client_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='commande', to='account.otherclient'),
        ),
    ]
