# Generated by Django 5.0.3 on 2024-06-20 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_commande_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cathegorie',
            name='id_modele',
        ),
    ]
