# Generated by Django 5.0.3 on 2024-06-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_cathegorie_id_modele'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='id_marque',
        ),
        migrations.AddField(
            model_name='piece',
            name='marque',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
