# Generated by Django 5.0.3 on 2024-06-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_piece_id_marque_piece_marque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pieceimage',
            old_name='thumbs',
            new_name='piece_id',
        ),
    ]
