# Generated by Django 5.0.3 on 2024-06-20 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Modele',
        ),
    ]
